---
abstract: 'Bitcoin module'
author:
  - grondilu
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Base: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: libbitcoin-perl
no_index:
  directory:
    - inc
    - t
requires:
  BerkeleyDB: 0
  Convert::ASN1: 0
  File::Map: 0
  perl: 5.14.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Perlover/libbitcoin-perl.git
version: 0.01
